# Target specific macros
TARGET = ex_c++

TARGET_CPP_SOURCES = MainController.cpp Distance.cpp Calibration.cpp LightFilter.cpp MyMotor.cpp Linetrace.cpp SelectCourse.cpp Course.cpp FreeRun.cpp StepDetection.cpp LineDetection.cpp
	
TOPPERS_OSEK_OIL_SOURCE = ./ex_c++.oil

# Don't modify below part
O_PATH ?= build

# makefile for C++(.cpp) build
include ../ecrobot/ecrobot++.mak
